# Generated by Django 5.2.1 on 2025-05-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3),
        ),
    ]
