# Generated by Django 5.2.1 on 2025-05-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_classschedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='class_group',
            field=models.CharField(default='BIT L400 Group C', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.UniqueConstraint(fields=('course', 'class_group', 'day_of_week'), name='unique_course_group_day'),
        ),
    ]
