# Generated by Django 5.2.1 on 2025-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_classschedule_class_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='program',
            field=models.CharField(default='BIT', max_length=100),
        ),
    ]
