# Generated by Django 5.2.1 on 2025-05-18 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_classschedule_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
