# Generated by Django 5.2.1 on 2025-05-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_classschedule_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
