# Generated by Django 5.2.1 on 2025-05-18 20:18

import attendance.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_lecturer'),
        ('attendance', '0006_alter_classschedule_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classschedule',
            name='unique_course_group_day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturers',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='lecturer',
            field=models.ForeignKey(default=attendance.models.get_first_lecturer, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lecturer'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.UniqueConstraint(fields=('course', 'class_group', 'day_of_week', 'lecturer'), name='unique_course_group_day'),
        ),
    ]
